[package]
authors = ["Jake Goulding <jake.goulding@gmail.com>"]
name = "join-to-subquery"
version = "0.1.0"

[dependencies]
diesel = { version = "0.14.0", features = ["sqlite"] }
diesel_codegen = { version = "0.14.0", features = ["sqlite"] }
dotenv = "0.9.0"
